COLORS = {
    "bg_main":      "#F8F9FA",
    "bg_card":      "#FFFFFF",
    "primary":      "#0D6EFD",
    "primary_dark": "#0A58CA",
    "success":      "#198754",
    "success_dark": "#146C43",
    "danger":       "#DC3545",
    "secondary":    "#6C757D",
    "border":       "#DEE2E6",
    "border_light": "#E9ECEF",
    "text_dark":    "#212529",
    "text_muted":   "#6C757D",
    "console_bg":   "#1E2329",
    "console_text": "#A8FF78",
    "console_info": "#79C0FF",
    "console_warn": "#FFD700",
    "console_err":  "#FF7B72",
    "header_bg":    "#0D6EFD",
    "feasible":     "#198754",
    "optimal_pt":   "#DC3545",
    "plot_bg":      "#FAFBFC",
}

FONTS = {
    "title":    ("Segoe UI", 15, "bold"),
    "subtitle": ("Segoe UI", 11, "bold"),
    "body":     ("Segoe UI", 10),
    "small":    ("Segoe UI", 9),
    "mono":     ("Consolas", 10),
    "header":   ("Segoe UI", 18, "bold"),
    "label":    ("Segoe UI", 10),
    "btn":      ("Segoe UI", 10, "bold"),
    "badge":    ("Segoe UI", 8, "bold"),
}
